version: '3'

services:
  backend:
    image: ghcr.io/spaicer/prototype-uc1-narrative1-digital-coil-2:latest
  frontend:
    image: ghcr.io/spaicer/digital-coil-ui-2:latest
    environment:
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend
    ports:
      - 8080:80
