/* tslint:disable */
/* eslint-disable */
/**
 * Digital Coil Backend Prototype
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Configuration } from './configuration'
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common'
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from './base'

/**
 * Features of the digital Coil
 * @export
 * @interface Features
 */
export interface Features {
  /**
   *
   * @type {number}
   * @memberof Features
   */
  breite: number
  /**
   *
   * @type {number}
   * @memberof Features
   */
  dicke_vorn: number
  /**
   *
   * @type {number}
   * @memberof Features
   */
  dicke_hinten: number
  /**
   *
   * @type {number}
   * @memberof Features
   */
  zugfestigkeit_a: number
  /**
   *
   * @type {number}
   * @memberof Features
   */
  zugfestigkeit_e: number
  /**
   *
   * @type {number}
   * @memberof Features
   */
  streckgrenze_a: number
  /**
   *
   * @type {number}
   * @memberof Features
   */
  streckgrenze_e: number
  /**
   *
   * @type {number}
   * @memberof Features
   */
  bruchdehnung_a: number
  /**
   *
   * @type {number}
   * @memberof Features
   */
  bruchdehnung_e: number
}
/**
 *
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
  /**
   *
   * @type {Array<ValidationError>}
   * @memberof HTTPValidationError
   */
  detail?: Array<ValidationError>
}
/**
 * Based on the Features, the machine learning algorithm provides a recommendation.
 * @export
 * @interface RecommendationOutput
 */
export interface RecommendationOutput {
  /**
   *
   * @type {number}
   * @memberof RecommendationOutput
   */
  cm50_einlauf: number
  /**
   *
   * @type {number}
   * @memberof RecommendationOutput
   */
  cm50_auslauf: number
  /**
   *
   * @type {number}
   * @memberof RecommendationOutput
   */
  cm70_einlauf: number
  /**
   *
   * @type {number}
   * @memberof RecommendationOutput
   */
  cm70_auslauf: number
  /**
   *
   * @type {number}
   * @memberof RecommendationOutput
   */
  bandzug: number
}
/**
 *
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
  /**
   *
   * @type {Array<string>}
   * @memberof ValidationError
   */
  loc: Array<string>
  /**
   *
   * @type {string}
   * @memberof ValidationError
   */
  msg: string
  /**
   *
   * @type {string}
   * @memberof ValidationError
   */
  type: string
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * Apply the model on the features and return recommendation.
     * @summary Detect Point Anomalies
     * @param {Features} features
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    detectPointAnomaliesGetRecommendationPost: async (
      features: Features,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'features' is not null or undefined
      assertParamExists(
        'detectPointAnomaliesGetRecommendationPost',
        'features',
        features
      )
      const localVarPath = `/get_recommendation`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter, options.query)
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        features,
        localVarRequestOptions,
        configuration
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
  return {
    /**
     * Apply the model on the features and return recommendation.
     * @summary Detect Point Anomalies
     * @param {Features} features
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async detectPointAnomaliesGetRecommendationPost(
      features: Features,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<RecommendationOutput>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.detectPointAnomaliesGetRecommendationPost(
          features,
          options
        )
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      )
    },
  }
}

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = DefaultApiFp(configuration)
  return {
    /**
     * Apply the model on the features and return recommendation.
     * @summary Detect Point Anomalies
     * @param {Features} features
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    detectPointAnomaliesGetRecommendationPost(
      features: Features,
      options?: any
    ): AxiosPromise<RecommendationOutput> {
      return localVarFp
        .detectPointAnomaliesGetRecommendationPost(features, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
  /**
   * Apply the model on the features and return recommendation.
   * @summary Detect Point Anomalies
   * @param {Features} features
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public detectPointAnomaliesGetRecommendationPost(
    features: Features,
    options?: any
  ) {
    return DefaultApiFp(this.configuration)
      .detectPointAnomaliesGetRecommendationPost(features, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
